[package]
name = "deduper-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "deduper_utils"
path = "src/lib.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
